SuiviImport.pyTraceback (most recent call last):
  File "d:\Users\Mcressei\AppData\Local\Programs\Python\Python310\Python scripts\SuiviImport.py", line 56, in <module>
    cursor.execute(insert_query, entries)
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Users\Mcressei\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`reusi`.`suivi`, CONSTRAINT `FK_EF7DE58B17A26983` FOREIGN KEY (`SuiviSignal_id`) REFERENCES `signal` (`id`))')
